FROM bitnami/postgresql-repmgr:13-debian-12

#based on https://github.com/pgvector/pgvector/ v0.7.4
#COPY /PgVector/vector.so /usr/lib/postgresql/14/lib
#COPY /PgVector/vector_control/* /usr/share/postgresql/14/extension
RUN mkdir /backups
RUN mkdir /scripts
COPY PostgresSlave/backup.sh /scripts/backup.sh
RUN chmod 0777 /docker-entrypoint-initdb.d/postgresSlave.sh
RUN chmod 0777 /scripts/backup.sh
