FROM bitnami/postgresql-repmgr:17.2.0
RUN chmod -R g+rwX /opt/bitnami
#COPY --chmod=0666 ./postgresMaster.sh /docker-entrypoint-initdb.d/postgresMaster.sh
#USER postgres
#COPY --chown=postgres:postgres PostgresqlDict/* /usr/share/postgresql/14/tsearch_data/

#based on https://github.com/pgvector/pgvector/ v0.7.4
#COPY /PgVector/vector.so /usr/lib/postgresql/14/lib
#COPY /PgVector/vector_control/* /usr/share/postgresql/14/extension
